version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: "/CodeBuild/dockerhub/username"
    DOCKERHUB_PASSWORD: "/CodeBuild/dockerhub/password"

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - echo "Building Docker image..."
      - IMAGE_NAME="$DOCKERHUB_USERNAME/simple-python-flask-app:latest"
      - docker build -t "$IMAGE_NAME" .
      - echo "Pushing Docker image to Docker Hub..."
      - docker push "$IMAGE_NAME"

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: .

